[build]
  publish = "dist/public"
  command = "npm run build"

[functions]
  directory = "dist/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
